import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/navbar/Navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>구루메디비</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
    </>
  );
};

export default Home;
