import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Map from '../components/map/Map';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>구루메디비</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Map />
    </>
  );
};

export default Home;
